-- =============================================
-- Thêm Ôn tập cuối kì
-- Chạy trong Supabase > SQL Editor
-- =============================================

-- 1. Thêm chương ôn tập cuối kì
INSERT INTO chapters (id, name, description) VALUES
(7, 'Ôn tập cuối kì', 'Tổng hợp kiến thức từ tất cả các chương')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;

-- 2. Câu hỏi ôn tập cuối kì (42 câu)
INSERT INTO questions (chapter_id, text, topic, correct, explanation, answers) VALUES
(7, 'Dịch vụ hướng kết nối sử dụng giao thức TCP để truyền tệp trong mô hình TCP/IP là giao thức nào?', 'Tầng ứng dụng', 'B', 'FTP là giao thức truyền tệp ở tầng ứng dụng và sử dụng TCP.', '[{"letter":"A","text":"HTTP"},{"letter":"B","text":"FTP"},{"letter":"C","text":"DNS"},{"letter":"D","text":"ARP"}]'),
(7, 'Một thông điệp HTTP Request thường gồm mấy phần?', 'HTTP', 'B', 'HTTP Request thường gồm dòng yêu cầu, header và body.', '[{"letter":"A","text":"2 phần"},{"letter":"B","text":"3 phần"},{"letter":"C","text":"4 phần"},{"letter":"D","text":"5 phần"}]'),
(7, 'Trong HTTP Request, phần Body thường chứa nội dung gì?', 'HTTP', 'B', 'Body chứa dữ liệu như form, JSON, XML hoặc tệp tải lên.', '[{"letter":"A","text":"Địa chỉ MAC của máy gửi"},{"letter":"B","text":"Dữ liệu client gửi lên server"},{"letter":"C","text":"Bảng định tuyến"},{"letter":"D","text":"Mã lỗi của server"}]'),
(7, 'Một thông điệp HTTP Response thường gồm mấy phần?', 'HTTP', 'C', 'HTTP Response gồm status line, header và body.', '[{"letter":"A","text":"1 phần"},{"letter":"B","text":"2 phần"},{"letter":"C","text":"3 phần"},{"letter":"D","text":"4 phần"}]'),
(7, 'HTTP khác HTTPS chủ yếu ở điểm nào?', 'HTTP', 'B', 'HTTPS là HTTP có thêm lớp bảo mật SSL/TLS để mã hóa dữ liệu.', '[{"letter":"A","text":"HTTPS dùng cáp quang còn HTTP dùng cáp đồng"},{"letter":"B","text":"HTTPS có mã hóa SSL/TLS, HTTP thì không"},{"letter":"C","text":"HTTP nhanh hơn trong mọi trường hợp"},{"letter":"D","text":"HTTP chỉ dùng trong mạng LAN"}]'),
(7, 'Có thể cấu hình DNS Server theo mấy cách cơ bản?', 'DNS', 'B', 'Thường có cấu hình thủ công hoặc nhận tự động qua DHCP.', '[{"letter":"A","text":"1 cách"},{"letter":"B","text":"2 cách"},{"letter":"C","text":"3 cách"},{"letter":"D","text":"4 cách"}]'),
(7, 'Giao thức trung tâm của hệ thống thư điện tử là gì?', 'Email', 'A', 'SMTP chủ yếu dùng để gửi thư điện tử.', '[{"letter":"A","text":"SMTP"},{"letter":"B","text":"POP3"},{"letter":"C","text":"IMAP"},{"letter":"D","text":"FTP"}]'),
(7, 'Giao thức tầng ứng dụng dùng để lấy thư điện tử từ mail server về máy người dùng qua TCP/IP là gì?', 'Email', 'C', 'Trong dạng câu hỏi cơ bản, đáp án thường là POP3.', '[{"letter":"A","text":"SMTP"},{"letter":"B","text":"DNS"},{"letter":"C","text":"POP3"},{"letter":"D","text":"ARP"}]'),
(7, 'Trong mô hình kiến trúc mạng nào có một máy luôn hoạt động để nhận và xử lý yêu cầu từ các máy khác?', 'Kiến trúc mạng', 'B', 'Mô hình Client-Server có máy chủ phục vụ cho các máy khách.', '[{"letter":"A","text":"Peer-to-Peer"},{"letter":"B","text":"Client-Server"},{"letter":"C","text":"Bus"},{"letter":"D","text":"Ring"}]'),
(7, 'Ưu điểm lớn nhất của kiến trúc mạng ngang hàng là gì?', 'Kiến trúc mạng', 'B', 'Peer-to-Peer dễ triển khai và ít tốn chi phí hơn.', '[{"letter":"A","text":"Quản lý tập trung tốt"},{"letter":"B","text":"Không cần máy chủ trung tâm, chi phí thấp"},{"letter":"C","text":"Bảo mật tuyệt đối"},{"letter":"D","text":"Luôn nhanh hơn Client-Server"}]'),
(7, 'Tầng giao vận có nhiệm vụ chính gì?', 'Tầng giao vận', 'B', 'Tầng giao vận chịu trách nhiệm truyền dữ liệu đầu cuối đến đầu cuối.', '[{"letter":"A","text":"Định tuyến gói tin"},{"letter":"B","text":"Truyền dữ liệu giữa các tiến trình đầu cuối"},{"letter":"C","text":"Truyền bit trên đường truyền"},{"letter":"D","text":"Phân giải tên miền"}]'),
(7, 'Trường checksum của TCP và UDP có độ dài bao nhiêu bit?', 'TCP/UDP', 'B', 'Checksum trong TCP và UDP đều dài 16 bit.', '[{"letter":"A","text":"8 bit"},{"letter":"B","text":"16 bit"},{"letter":"C","text":"32 bit"},{"letter":"D","text":"64 bit"}]'),
(7, 'Chức năng nào sau đây thuộc tầng giao vận?', 'Tầng giao vận', 'A', 'Tầng giao vận dùng port để phân biệt ứng dụng nguồn và đích.', '[{"letter":"A","text":"Ghép kênh và tách kênh theo port"},{"letter":"B","text":"Phân giải IP sang MAC"},{"letter":"C","text":"Định tuyến giữa các mạng"},{"letter":"D","text":"Mã hóa tín hiệu điện"}]'),
(7, 'Trong UDP, trường nào cho biết độ dài toàn bộ segment?', 'UDP', 'C', 'Trường Length trong UDP cho biết độ dài datagram.', '[{"letter":"A","text":"Checksum"},{"letter":"B","text":"Port"},{"letter":"C","text":"Length"},{"letter":"D","text":"Sequence Number"}]'),
(7, 'Kích thước tối thiểu của phần header UDP là bao nhiêu?', 'UDP', 'B', 'UDP header có độ dài cố định là 8 byte.', '[{"letter":"A","text":"4 byte"},{"letter":"B","text":"8 byte"},{"letter":"C","text":"16 byte"},{"letter":"D","text":"20 byte"}]'),
(7, 'Khi client nhận được gói FIN/ACK từ server trong quá trình kết thúc kết nối TCP, client sẽ làm gì?', 'TCP', 'A', 'Khi nhận FIN hoặc FIN/ACK, phía còn lại phải gửi ACK xác nhận.', '[{"letter":"A","text":"Gửi ACK xác nhận"},{"letter":"B","text":"Gửi SYN mới"},{"letter":"C","text":"Gửi lại toàn bộ dữ liệu"},{"letter":"D","text":"Bỏ qua gói tin"}]'),
(7, 'Nếu tốc độ xử lý dữ liệu ở trạm thu chậm hơn tốc độ gửi của trạm phát thì điều gì dễ xảy ra?', 'Kiểm soát lưu lượng', 'B', 'Khi bên nhận không xử lý kịp, buffer dễ bị đầy.', '[{"letter":"A","text":"Địa chỉ IP bị đổi"},{"letter":"B","text":"Bộ đệm phía nhận bị tràn"},{"letter":"C","text":"Cổng mạng tự đóng"},{"letter":"D","text":"Router bị tắt"}]'),
(7, 'UDP có cơ chế kiểm soát lưu lượng hay không?', 'UDP', 'C', 'UDP không có cơ chế kiểm soát lưu lượng như TCP.', '[{"letter":"A","text":"Có đầy đủ như TCP"},{"letter":"B","text":"Có nhưng chỉ trong LAN"},{"letter":"C","text":"Không"},{"letter":"D","text":"Chỉ có khi gửi video"}]'),
(7, 'Thời gian thiết lập kết nối của UDP là bao nhiêu?', 'UDP', 'D', 'UDP là giao thức không hướng kết nối nên không cần thiết lập trước.', '[{"letter":"A","text":"1 bước"},{"letter":"B","text":"2 bước"},{"letter":"C","text":"3 bước"},{"letter":"D","text":"Bằng 0"}]'),
(7, 'Dịch vụ nào yêu cầu thiết lập một đường đi logic trước khi các gói tin được gửi đi?', 'Tầng mạng', 'B', 'Dịch vụ hướng kết nối yêu cầu thiết lập đường đi trước.', '[{"letter":"A","text":"Dịch vụ không liên kết"},{"letter":"B","text":"Dịch vụ hướng kết nối"},{"letter":"C","text":"Dịch vụ quảng bá"},{"letter":"D","text":"Dịch vụ multicast"}]'),
(7, 'Dịch vụ nào gửi ngay các gói tin mà không cần thiết lập đường đi trước?', 'Tầng mạng', 'C', 'Dịch vụ không liên kết xử lý từng gói tin độc lập.', '[{"letter":"A","text":"Dịch vụ hướng kết nối"},{"letter":"B","text":"Dịch vụ mạch ảo"},{"letter":"C","text":"Dịch vụ không liên kết"},{"letter":"D","text":"Dịch vụ đồng bộ"}]'),
(7, 'Định tuyến là gì?', 'Tầng mạng', 'A', 'Định tuyến là chức năng cốt lõi của tầng mạng.', '[{"letter":"A","text":"Quá trình chọn đường đi cho gói tin từ nguồn đến đích"},{"letter":"B","text":"Quá trình đổi địa chỉ MAC"},{"letter":"C","text":"Quá trình nén dữ liệu"},{"letter":"D","text":"Quá trình đặt tên miền"}]'),
(7, 'Chức năng quan trọng nhất của tầng mạng là gì?', 'Tầng mạng', 'B', 'Tầng mạng đảm nhiệm địa chỉ logic, định tuyến và chuyển tiếp.', '[{"letter":"A","text":"Mã hóa dữ liệu"},{"letter":"B","text":"Định tuyến và chuyển tiếp gói tin"},{"letter":"C","text":"Gán port cho ứng dụng"},{"letter":"D","text":"Kiểm tra lỗi bit ở tầng vật lý"}]'),
(7, 'Mạng tùy biến di động là gì?', 'Tầng mạng', 'B', 'Đây là mạng mà các nút có thể tự kết nối và định tuyến cho nhau.', '[{"letter":"A","text":"Mạng chỉ dùng cáp quang"},{"letter":"B","text":"Mạng không dây tự tổ chức, không cần hạ tầng cố định"},{"letter":"C","text":"Mạng chỉ hoạt động trong phòng máy"},{"letter":"D","text":"Mạng chỉ có một máy chủ"}]'),
(7, 'Nguyên nhân nào có thể gây tắc nghẽn mạng?', 'Tầng mạng', 'D', 'Tắc nghẽn thường do lưu lượng quá lớn so với khả năng xử lý.', '[{"letter":"A","text":"Quá nhiều gói tin đi vào mạng"},{"letter":"B","text":"Băng thông hạn chế"},{"letter":"C","text":"Bộ đệm thiết bị mạng có giới hạn"},{"letter":"D","text":"Cả A, B, C"}]'),
(7, 'Giao thức IP hoạt động ở tầng nào?', 'IP', 'C', 'IP là giao thức cốt lõi của tầng mạng.', '[{"letter":"A","text":"Tầng ứng dụng"},{"letter":"B","text":"Tầng giao vận"},{"letter":"C","text":"Tầng mạng"},{"letter":"D","text":"Tầng liên kết dữ liệu"}]'),
(7, 'Địa chỉ IPv4 có độ dài bao nhiêu bit?', 'IPv4', 'B', 'IPv4 dài 32 bit.', '[{"letter":"A","text":"16 bit"},{"letter":"B","text":"32 bit"},{"letter":"C","text":"64 bit"},{"letter":"D","text":"128 bit"}]'),
(7, 'Địa chỉ IPv6 có độ dài bao nhiêu bit?', 'IPv6', 'C', 'IPv6 dài 128 bit.', '[{"letter":"A","text":"64 bit"},{"letter":"B","text":"96 bit"},{"letter":"C","text":"128 bit"},{"letter":"D","text":"256 bit"}]'),
(7, 'Cơ chế chuyển đổi địa chỉ mạng thường được nhắc đến là gì?', 'NAT', 'B', 'NAT là cơ chế chuyển đổi địa chỉ mạng.', '[{"letter":"A","text":"FTP"},{"letter":"B","text":"NAT"},{"letter":"C","text":"ICMP"},{"letter":"D","text":"SMTP"}]'),
(7, 'Router là thiết bị hoạt động chủ yếu ở tầng nào?', 'Router', 'C', 'Router dùng để định tuyến gói tin giữa các mạng.', '[{"letter":"A","text":"Tầng vật lý"},{"letter":"B","text":"Tầng liên kết dữ liệu"},{"letter":"C","text":"Tầng mạng"},{"letter":"D","text":"Tầng ứng dụng"}]'),
(7, 'Chức năng của tầng liên kết dữ liệu là gì?', 'Tầng liên kết', 'B', 'Tầng liên kết dữ liệu làm việc theo kiểu node-to-node.', '[{"letter":"A","text":"Định tuyến liên mạng"},{"letter":"B","text":"Truyền dữ liệu tin cậy giữa hai nút liền kề"},{"letter":"C","text":"Gửi email"},{"letter":"D","text":"Cấp phát tên miền"}]'),
(7, 'Địa chỉ MAC là gì?', 'MAC', 'B', 'MAC là địa chỉ phần cứng gắn với card mạng.', '[{"letter":"A","text":"Địa chỉ logic trên Internet"},{"letter":"B","text":"Địa chỉ vật lý của thiết bị mạng"},{"letter":"C","text":"Tên miền của máy tính"},{"letter":"D","text":"Địa chỉ email"}]'),
(7, 'Giao thức nào dùng để tìm địa chỉ vật lý khi biết địa chỉ IPv4 của máy đích?', 'ARP', 'C', 'ARP dùng để phân giải IPv4 sang địa chỉ MAC.', '[{"letter":"A","text":"DNS"},{"letter":"B","text":"FTP"},{"letter":"C","text":"ARP"},{"letter":"D","text":"ICMP"}]'),
(7, 'Hai kỹ thuật cấp phát tĩnh để chia sẻ kênh truyền là gì?', 'FDM/TDM', 'B', 'FDM chia theo tần số, TDM chia theo thời gian.', '[{"letter":"A","text":"ARP và RARP"},{"letter":"B","text":"FDM và TDM"},{"letter":"C","text":"TCP và UDP"},{"letter":"D","text":"HTTP và FTP"}]'),
(7, 'Phương pháp chia sẻ kênh ALOHA ra đời vào khoảng năm nào?', 'ALOHA', 'B', 'ALOHA được biết đến từ khoảng năm 1970.', '[{"letter":"A","text":"1960"},{"letter":"B","text":"1970"},{"letter":"C","text":"1980"},{"letter":"D","text":"1990"}]'),
(7, 'Thiết bị cơ bản và phổ biến nhất hoạt động ở tầng liên kết dữ liệu trong mạng LAN hiện đại là gì?', 'Switch', 'A', 'Switch là thiết bị tiêu biểu của tầng liên kết dữ liệu.', '[{"letter":"A","text":"Switch"},{"letter":"B","text":"Router"},{"letter":"C","text":"Modem"},{"letter":"D","text":"Hub"}]'),
(7, 'Chuyển mạch kênh là gì?', 'Chuyển mạch', 'B', 'Chuyển mạch kênh thiết lập kênh riêng trước khi truyền.', '[{"letter":"A","text":"Dữ liệu được chia thành các gói độc lập"},{"letter":"B","text":"Một đường truyền riêng được thiết lập trong suốt phiên liên lạc"},{"letter":"C","text":"Gửi dữ liệu bằng quảng bá"},{"letter":"D","text":"Định tuyến động giữa các router"}]'),
(7, 'Chuyển mạch gói là gì?', 'Chuyển mạch', 'A', 'Chuyển mạch gói chia dữ liệu thành các gói để truyền.', '[{"letter":"A","text":"Dữ liệu được chia thành các gói và truyền qua mạng"},{"letter":"B","text":"Dữ liệu truyền nguyên khối trên một kênh riêng"},{"letter":"C","text":"Chỉ dùng trong mạng điện thoại cũ"},{"letter":"D","text":"Không cần địa chỉ đích"}]'),
(7, 'Có mấy nguyên nhân cơ bản dẫn đến sai lệch tín hiệu?', 'Tầng vật lý', 'B', 'Ba nguyên nhân cơ bản là suy hao, nhiễu và méo dạng.', '[{"letter":"A","text":"2"},{"letter":"B","text":"3"},{"letter":"C","text":"4"},{"letter":"D","text":"5"}]'),
(7, 'Sóng viba là gì?', 'Tầng vật lý', 'B', 'Sóng viba là sóng điện từ tần số cao, dùng trong nhiều hệ thống truyền thông.', '[{"letter":"A","text":"Một loại cáp đồng"},{"letter":"B","text":"Một loại sóng điện từ tần số cao dùng trong truyền thông vô tuyến"},{"letter":"C","text":"Một giao thức định tuyến"},{"letter":"D","text":"Một dạng địa chỉ IP"}]'),
(7, 'Modem là thiết bị hoạt động chủ yếu ở tầng nào?', 'Tầng vật lý', 'A', 'Modem điều chế và giải điều chế tín hiệu, thuộc chủ yếu về tầng vật lý.', '[{"letter":"A","text":"Tầng vật lý"},{"letter":"B","text":"Tầng mạng"},{"letter":"C","text":"Tầng ứng dụng"},{"letter":"D","text":"Tầng giao vận"}]'),
(7, 'Hub là thiết bị hoạt động ở tầng nào?', 'Tầng vật lý', 'A', 'Hub chỉ phát tín hiệu ra các cổng, không xử lý địa chỉ nên thuộc tầng vật lý.', '[{"letter":"A","text":"Tầng vật lý"},{"letter":"B","text":"Tầng liên kết dữ liệu"},{"letter":"C","text":"Tầng mạng"},{"letter":"D","text":"Tầng giao vận"}]');
